version: '3.5'

services:

    ### Replace Backend here !!! ###
    # react-endpoint:
    #     build: ./junior-react-endpoint
    #     ports:
    #         - "4000:4000"
    #     container_name: react-endpoint

    main-app-prod:
        build:
            context: ./react-task-update
            dockerfile: Dockerfile.prod
        environment:
            - REACT_APP_ENDPOINT=http://localhost:4000/
        depends_on:
            - react-endpoint
        ports:
            - "3000:3000"
        container_name: react-task-main-app-prod
