export enum cartConstants {
  ADD_TO_CART = 'ADD_TO_CART',
  CHANGE_ITEM_COUNT = 'CHANGE_ITEM_COUNT',
  CHANGE_ITEM_CART_IMAGE = 'CHANGE_ITEM_CART_IMAGE',
  GO_TO_CART = 'GO_TO_CART',

  CLEAR = 'CLEAR',
}
