export enum homepageConstants {
  GET_CURRENCIES_REQUEST = 'GET_CURRENCIES_REQUEST',
  GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS',
  GET_CURRENCIES_FAILURE = 'GET_CURRENCIES_FAILURE',

  SELECT_CURRENCY = 'SELECT_CURRENCY',

  GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST',
  GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE',

  GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST',
  GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE',

  CHANGE_CATEGORY = 'CHANGE_CATEGORY',
  SELECT_PRODUCT = 'SELECT_PRODUCT',
  CART_VIEW = 'CART_VIEW',

  CLEAR = 'CLEAR',
}
